plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nereus.operations'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nereus.operations'
        minSdk 24
        targetSdk 35
        versionCode 11
        versionName '0.3.8'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}
