plugins { id 'com.android.application' }

android {
    namespace 'com.nereus.volgadrift'
    compileSdk 35
    defaultConfig {
        applicationId 'com.nereus.volgadrift'
        minSdk 26
        targetSdk 35
        versionCode 13
        versionName '1.6.3'
    }
    buildTypes { release { minifyEnabled false } }
}
